In [9]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'asta':np.random.normal(size=200)})
# example dataset of normally distributed data. 

df

         Data
0   -0.066416
1    1.693552
2    0.441913
3    1.470194
4   -1.693721
5    0.057757
6    0.717478
7   -1.740175
8   -0.025828
9   -0.277841
10   0.950919
11   0.411363
12  -0.218312
13  -1.206166
14  -0.598281
15  -0.194179
16  -0.593742
17   0.283455
18   0.581725
19  -0.252539
20  -0.482146
21   0.878624
22  -0.053343
23   0.295404
24   0.241627
25  -0.299215
26  -0.331365
27  -1.071434
28   0.710636
29  -0.429270
..        ...
170  0.434655
171  0.667421
172  0.318445
173  0.958356
174  0.893566
175 -0.574318
176 -1.355135
177  0.664004
178  1.079608
179  0.264136
180 -0.330210
181 -1.223914
182  0.807258
183 -0.516009
184  0.077319
185  0.325066
186  0.326371
187 -0.310329
188  0.958479
189  1.249629
190  1.554293
191  1.073725
192 -1.296898
193  0.797963
194  1.264352
195 -0.109969
196  1.140012
197  0.468924
198  0.373964
199 -0.525437

[200 rows x 1 columns]

In [6]:
df[np.abs(df.Data-df.Data.mean()) <= (3*df.Data.std())]
# keep only the ones that are within +3 to -3 standard deviations in the column 'Data'.

         Data
0    1.305361
1    0.090759
2   -1.008340
3   -0.102144
4    0.335709
5   -0.142094
6    0.016283
7   -0.474638
8    0.676851
9   -1.314996
10  -0.229654
11  -0.734631
12  -1.607355
13  -1.708835
14   0.810276
15   0.117513
16  -0.326538
17   0.533930
18   2.338993
19  -2.478816
20   0.166291
21   0.922480
22  -0.010434
23   0.313581
24  -1.066793
25   0.654716
26   0.176367
27  -0.363005
28  -0.899200
29   0.339136
..        ...
170  2.143355
171  0.712471
172 -1.276911
173 -0.659606
174 -0.931920
175 -0.895863
176  1.511697
177  0.423711
178  0.240047
179  0.837895
180 -1.606656
181  0.158030
182 -0.997063
183  0.308333
184  1.846642
185  0.055021
186  1.107170
187 -1.421403
188  0.039975
189 -0.261507
190  0.249728
191 -0.248480
192  0.525949
193  0.415668
194 -0.984529
195 -0.788045
196  0.252911
197  0.771735
198  0.861435
199  0.321801

[200 rows x 1 columns]

In [7]:
df[~(np.abs(df.Data-df.Data.mean()) > (3*df.Data.std()))]
# or if you prefer the other way around

         Data
0    1.305361
1    0.090759
2   -1.008340
3   -0.102144
4    0.335709
5   -0.142094
6    0.016283
7   -0.474638
8    0.676851
9   -1.314996
10  -0.229654
11  -0.734631
12  -1.607355
13  -1.708835
14   0.810276
15   0.117513
16  -0.326538
17   0.533930
18   2.338993
19  -2.478816
20   0.166291
21   0.922480
22  -0.010434
23   0.313581
24  -1.066793
25   0.654716
26   0.176367
27  -0.363005
28  -0.899200
29   0.339136
..        ...
170  2.143355
171  0.712471
172 -1.276911
173 -0.659606
174 -0.931920
175 -0.895863
176  1.511697
177  0.423711
178  0.240047
179  0.837895
180 -1.606656
181  0.158030
182 -0.997063
183  0.308333
184  1.846642
185  0.055021
186  1.107170
187 -1.421403
188  0.039975
189 -0.261507
190  0.249728
191 -0.248480
192  0.525949
193  0.415668
194 -0.984529
195 -0.788045
196  0.252911
197  0.771735
198  0.861435
199  0.321801

[200 rows x 1 columns]

In [10]:
df.Data-df.Data.mean()

0.03296506032695415